# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20180521_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brend',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='myshop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044f'),
        ),
    ]
