# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440', 'verbose_name_plural': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0456'},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='autor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.TextField(max_length=4000, verbose_name='\u043a\u043e\u043c\u0435\u043d\u0442\u0430\u0440'),
        ),
    ]
