# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20181111_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
