# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180527_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': '\u0422\u043e\u0432\u0430\u0440 \u0432 \u0437\u0430\u043a\u0430\u0437\u0456', 'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u0438 \u0432 \u0437\u0430\u043a\u0430\u0437\u0456'},
        ),
    ]
